apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-lake-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: postgres
            repoURL: https://charts.bitnami.com/bitnami
            chart: postgresql
            targetRevision: 15.5.11
            namespace: data-lake
            valueFiles:
              - charts/telecom/data-lake-infra/postgres/values.yaml

          - name: airflow
            repoURL: https://airflow.apache.org
            chart: airflow
            targetRevision: 1.13.0
            namespace: data-lake
            valueFiles:
              - charts/telecom/data-lake-infra/airflow/values.yaml

          - name: trino
            repoURL: https://trinodb.github.io/charts
            chart: trino
            targetRevision: 0.13.0
            namespace: data-lake
            valueFiles:
              - charts/telecom/data-lake-infra/trino/values.yaml

          - name: metabase
            repoURL: https://pmint93.github.io/helm-charts
            chart: metabase
            targetRevision: 0.12.0
            namespace: data-lake
            valueFiles:
              - charts/telecom/data-lake-infra/metabase/values.yaml

          - name: warehouse-pvc
            repoURL: https://github.com/mkarthikd/Python-base-webapp.git
            path: charts/telecom/data-lake-infra/k8s/storage
            targetRevision: main
            namespace: data-lake

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        path: '{{path}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: '{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

