apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telecom
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      telecom=docker.io/karthikmd06/telecom-customer-insights
    argocd-image-updater.argoproj.io/telecom.update-strategy: semver
    argocd-image-updater.argoproj.io/telecom.allow-tags: regexp:^([0-9]+\.[0-9]+\.[0-9]+)$
    argocd-image-updater.argoproj.io/telecom.pull-secret: pullsecret:argocd/dockerhub
    argocd-image-updater.argoproj.io/telecom.values: "image.tag"
    argocd-image-updater.argoproj.io/git-credential-secret: git-creds
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/mkarthikd/Python-base-webapp.git
    targetRevision: main
    path: charts/telecom
    helm:
      releaseName: telecom
  destination:
    server: https://kubernetes.default.svc
    namespace: telecom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true