apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-api
  namespace: {{ .Values.namespace }}
  labels:
    app: telecom-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: telecom-api
  template:
    metadata:
      labels:
        app: telecom-api
    spec:
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: telecom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: CUSTOMER_DATA
              value: {{ .Values.env.CUSTOMER_DATA | quote }}
            {{- if .Values.secrets.enabled }}
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: APP_SECRET
            {{- end }}
          volumeMounts:
            - name: data-storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
