apiVersion: batch/v1
kind: Job
metadata:
  name: load-customers
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: csv-loader
          image: python:3.11-slim
          command: ["python", "-u", "/scripts/load_csv.py"]
          env:
            - name: CUSTOMER_DATA
              value: {{ .Values.env.CUSTOMER_DATA | quote }}
            - name: POSTGRES_URL
              value: "postgresql+asyncpg://iceberg:icebergpass@postgres-rw.data-lake.svc.cluster.local:5432/iceberg"
          volumeMounts:
            - name: customer-data
              mountPath: {{ .Values.env.CUSTOMER_DATA | quote }}
            - name: loader-scripts
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: customer-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: loader-scripts
          configMap:
            name: load-csv-scripts
