apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: telecom
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: minio-credentials
        property: MINIO_ENDPOINT
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: minio-credentials
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: minio-credentials
        property: MINIO_SECRET_KEY
